<a href="https://colab.research.google.com/github/IvesYan9/Data-scientists-learning/blob/ch2/ch2%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84%E9%83%A8%E5%88%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

# 視覺化函式庫
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 顯示到小數第3位
%precision 3

'%.3f'

In [ ]:
#設定初始值確定產生的隨機亂數序列固定
random.seed(1)

data = np.array([9, 2, 3, 4, 10, 7, 8, 1, 5])

print(random.choice(data, 10))

[ 7  5  7  9  9  2  1  8  3 10]


In [ ]:
#practice
data = np.arange(51)
#產生50個數的陣列

datar = data.sum()
datar

1275

In [ ]:
#practice
random.seed(0)

data = np.random.randn(10)
#產生10個數的隨機陣列

data.max(),data.min(),data.sum()


(2.241, -0.977, 7.380)

In [ ]:
#practice

data = np.ones((5, 5), dtype = np.int64)

data = data * 3

data2 = data.dot(data)

data2

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]], dtype=int64)

In [ ]:
#ans
data = np.ones((5, 5), dtype = 'i') * 3

data

data.dot(data)

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])